// ═══════════════════════════════════════════
//  QUEEN ALINA MD 2.0 - AI CODE
// ═══════════════════════════════════════════

import axios from 'axios';

export default {
    command: 'aicode',
    aliases: ['codeai', 'program'],
    description: 'Generate code with AI',
    category: 'ai',
    execute: async (ctx) => {
        const { fullArgs, reply } = ctx;

        if (!fullArgs) {
            return await reply('❌ Please provide a coding request!\n\nUsage: *.aicode <description>*');
        }

        try {
            await reply('💻 *Queen Alina AI* is coding...');

            const apiUrl = `https://api.nexoracle.com/ai/chatgpt?apikey=free_key@maher_apis&q=${encodeURIComponent('Write code for: ' + fullArgs)}`;
            const response = await axios.get(apiUrl, { timeout: 30000 });

            if (response.data && response.data.result) {
                await reply(`💻 *AI Generated Code*\n\n${response.data.result}\n\n_Generated by Queen Alina AI_`);
            } else {
                await reply('❌ Failed to generate code!');
            }
        } catch (error) {
            await reply(`❌ Error: ${error.message}`);
        }
    }
};
